[versions]
junit = "6.0.1"
jspecify = "1.0.0"
paper-api = "1.21.10-R0.1-SNAPSHOT"
minecraft = "1.21.10"
fabric-loom = "1.13.3"
fabric-api = "0.138.0+1.21.10"
fabric-loader = "0.17.3"
sponge-api = "17.0.0-SNAPSHOT"
minestom = "2025.10.31-1.21.10"
maven-publish = "0.34.0"

[libraries]
junit-bom = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
fabric-minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
sponge-api = { module = "org.spongepowered:spongeapi", version.ref = "sponge-api" }
minestom-api = { module = "net.minestom:minestom", version.ref = "minestom" }

[bundles]
junit = ["junit-bom", "junit-jupiter"]

[plugins]
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
